#!/bin/bash

sudo chown -R mozbot:mozbot   /usr/local/mozbot
sudo chmod -R u+rw,g+rw,o-rwx /usr/local/mozbot
sudo find                     /usr/local/mozbot -perm 760 -print0 | xargs -r -0 sudo chmod 770 
#sudo restorecon -RvF         /usr/local/mozbot

